export const states = [
  { State: 'Alabama' },
  { State: 'Alaska' },
  { State: 'Arizona' },
  { State: 'Arkansas' },
  { State: 'California' },
  { State: 'Colorado' },
  { State: 'Connecticut' },
  { State: 'Delaware' },
  // { State: 'District of Columbia' },
  { State: 'Florida' },
  { State: 'Georgia' },
  // { State: 'Hawaii' },
  { State: 'Idaho' },
  { State: 'Illinois' },
  { State: 'Indiana' },
  { State: 'Iowa' },
  { State: 'Kansas' },
  { State: 'Kentucky' },
  { State: 'Louisiana' },
  { State: 'Maine' },
  { State: 'Montana' },
  { State: 'Nebraska' },
  { State: 'Nevada' },
  { State: 'New Hampshire' },
  { State: 'New Jersey' },
  { State: 'New Mexico' },
  { State: 'New York' },
  { State: 'North Carolina' },
  { State: 'North Dakota' },
  { State: 'Ohio' },
  { State: 'Oklahoma' },
  { State: 'Oregon' },
  { State: 'Maryland' },
  { State: 'Massachusetts' },
  { State: 'Michigan' },
  { State: 'Minnesota' },
  { State: 'Mississippi' },
  { State: 'Missouri' },
  { State: 'Pennsylvania' },
  { State: 'Rhode Island' },
  { State: 'South Carolina' },
  { State: 'South Dakota' },
  { State: 'Tennessee' },
  { State: 'Texas' },
  { State: 'Utah' },
  { State: 'Vermont' },
  { State: 'Virginia' },
  { State: 'Washington' },
  { State: 'West Virginia' },
  { State: 'Wisconsin' },
  { State: 'Wyoming' },
];
